import { readdir, readFile, stat, mkdir, writeFile, copyFile } from 'fs/promises'
import { join, basename, dirname } from 'path'
import { existsSync, readFileSync } from 'fs'
import { app } from 'electron'
import AdmZip from 'adm-zip'
import { getConfig, type Language } from './appConfig'
import { CCPIT_VERSION, GITHUB_URL, CLAUDE_CODE_DOCS, AI_GUIDES } from './constants'

interface ScannedFile {
  path: string
  name: string
  lines: number
  sizeBytes: number
  category: 'claude-md' | 'rules' | 'skills' | 'settings' | 'other'
}

/** CC 構成ファイルの検出対象パターン */
const SCAN_TARGETS = [
  { glob: 'CLAUDE.md', category: 'claude-md' as const },
  { glob: '.claude/settings.json', category: 'settings' as const },
  { glob: '.claude/settings.local.json', category: 'settings' as const },
]

const SCAN_DIRS = [
  { dir: '.claude/rules', category: 'rules' as const },
  { dir: '.claude/skills', category: 'skills' as const },
]

/** 指定パスの CC 構成ファイルをスキャン */
export async function scanProject(projectPath: string): Promise<ScannedFile[]> {
  const results: ScannedFile[] = []

  // 単体ファイルチェック
  for (const target of SCAN_TARGETS) {
    const fullPath = join(projectPath, target.glob)
    if (existsSync(fullPath)) {
      const content = await readFile(fullPath, 'utf-8')
      const info = await stat(fullPath)
      results.push({
        path: fullPath,
        name: target.glob,
        lines: content.split('\n').length,
        sizeBytes: info.size,
        category: target.category,
      })
    }
  }

  // ディレクトリスキャン
  for (const { dir, category } of SCAN_DIRS) {
    const dirPath = join(projectPath, dir)
    if (!existsSync(dirPath)) continue
    try {
      const entries = await readdir(dirPath, { withFileTypes: true })
      for (const entry of entries) {
        if (!entry.isFile()) continue
        const fullPath = join(dirPath, entry.name)
        const content = await readFile(fullPath, 'utf-8')
        const info = await stat(fullPath)
        results.push({
          path: fullPath,
          name: `${dir}/${entry.name}`,
          lines: content.split('\n').length,
          sizeBytes: info.size,
          category,
        })
      }
    } catch {
      // ディレクトリ読み取り失敗は無視
    }
  }

  // ~/.claude/ もスキャン
  const userClaudeDir = join(app.getPath('home'), '.claude')
  if (existsSync(userClaudeDir) && !projectPath.includes('.claude')) {
    for (const target of SCAN_TARGETS) {
      const name = basename(target.glob)
      const fullPath = join(userClaudeDir, name)
      if (existsSync(fullPath) && !results.some((r) => r.path === fullPath)) {
        const content = await readFile(fullPath, 'utf-8')
        const info = await stat(fullPath)
        results.push({
          path: fullPath,
          name: `~/.claude/${name}`,
          lines: content.split('\n').length,
          sizeBytes: info.size,
          category: target.category,
        })
      }
    }

    for (const { dir, category } of SCAN_DIRS) {
      const dirName = dir.replace('.claude/', '')
      const dirPath = join(userClaudeDir, dirName)
      if (!existsSync(dirPath)) continue
      try {
        const entries = await readdir(dirPath, { withFileTypes: true })
        for (const entry of entries) {
          if (!entry.isFile()) continue
          const fullPath = join(dirPath, entry.name)
          if (results.some((r) => r.path === fullPath)) continue
          const content = await readFile(fullPath, 'utf-8')
          const info = await stat(fullPath)
          results.push({
            path: fullPath,
            name: `~/.claude/${dirName}/${entry.name}`,
            lines: content.split('\n').length,
            sizeBytes: info.size,
            category,
          })
        }
      } catch {
        // skip
      }
    }
  }

  return results
}

/** Conversion Pack テンプレート（日本語） */
function cpTemplateJa(
  version: string,
  githubUrl: string,
  docs: typeof CLAUDE_CODE_DOCS,
  scannedFilesSection: string,
  generatedAt: string,
  sourceLines: number
): string {
  return `# Conversion Pack — MANX Protocol Migration

> Generated by CCPIT v${version} | Protocol Interlock Tower

---
## あなたの役割

あなたは CCPIT（Claude Code Protocol Interlock Tower）の Migration アシスタントです。
ユーザーの既存 CLAUDE.md を MANX Protocol に準拠した階層構造に分解します。

**あなたが守るべき原則:**
1. **情報欠落ゼロ。** 元の CLAUDE.md に書かれたルールは 1 行も落とさない。意図的に除外する場合のみ、カバレッジマップに理由を明記する
2. **P1 は 30〜50 行。** 身分証明書。全セッションで常時ロードされる。ここに入れすぎるとコンテキストを浪費する
3. **P2 は各 20 行以下。** 短いリマインダー。常時 or glob でロード。YAML フロントマター付き。description は行為ベース（「〜する際に発火する」）
4. **P3 は行数制限なし。** 詳細手順書。オンデマンドロード。YAML フロントマター付き
5. **分解後に必ずカバレッジマップを出力。** 元の全セクションの対応先を漏れなく示す

**応答の口調:**
- ユーザーへの応答は丁寧語で行ってください
- 元の CLAUDE.md 内に実装 AI 向けのカジュアルな口調（「俺は」「〜するな」等）が含まれていても、それはコンバート対象のルール文面であり、あなたの応答口調ではありません

---
## 重要: 最新の Claude Code 仕様を確認してください

作業を開始する前に、以下の公式ドキュメントを必ず参照し、
現在の Claude Code の仕様と矛盾がないことを確認してください:

- CLAUDE.md の仕様: ${docs.memory}
- settings.json の仕様: ${docs.settings}
- rules/ の仕様: ${docs.rules}
- skills/ の仕様: ${docs.skills}
- hooks の仕様: ${docs.hooks}

Claude Code は更新が早く、ファイル構造・YAML フロントマター・
settings.json のスキーマが変わる可能性があります。
本 Conversion Pack の振り分け基準より公式ドキュメントが優先します。
公式仕様と矛盾を検出した場合は、カバレッジマップの備考欄に記載してください。

---
## 詳細な振り分けガイド（必ず読んでから作業を開始してください）

以下の URL にアクセスし、振り分け基準の詳細を確認してください:
${AI_GUIDES.ja.conversion}

MANX Protocol の全体像:
${AI_GUIDES.ja.summary}

---
## 既存構成ファイル

${scannedFilesSection}

---
## 出力要求

以下の構造を持つ .pit ファイル（ZIP 形式）を生成し、ダウンロード可能にしてください。

### 生成方法

Python の zipfile モジュールを使用し、以下の手順で .pit ファイルを生成してください:

1. 分解結果の各ファイル内容を変数に格納する
2. zipfile.ZipFile で ZIP を作成する
3. 各ファイルを writestr でディレクトリ構造付きで格納する
4. 拡張子を .pit にしてダウンロードリンクを提示する

### 重要: .pit ファイルの用途
生成した .pit ファイルはユーザーが CCPIT アプリにインポートして使用します。
ユーザーが手動で ZIP を展開して配置する必要はありません。
.pit ファイルを生成しダウンロードリンクを提示するところまでがあなたの仕事です。

### .pit 内部構造（全て必須）

\`\`\`
conversion_{YYYYMMDD}_{HHMM}.pit
├── CLAUDE.md                    ← P1（30〜50 行）
├── rules/                       ← P2（各 20 行以下、YAML フロントマター付き）
│   └── {name}.md
├── skills/                      ← P3（YAML フロントマター付き）
│   └── {name}/SKILL.md
├── coverage-map.md              ← カバレッジマップ
└── metrics.yaml                 ← 計測メトリクス
\`\`\`

### P1: CLAUDE.md
30〜50 行。身分・価値観・出力・信頼境界・インターロック表。

### P2: rules/
各ファイル 20 行以下。YAML フロントマター必須。
description は行為ベース（「〜する際に発火する」）。
ファイルパターンで発火条件を絞る場合は paths フィールド（配列）を使用。

\`\`\`markdown
---
description: （行為ベース「〜する際に発火する」）
paths:
  - "**/*.ts"
---
（内容。20 行以下）
\`\`\`

### P3: skills/
YAML フロントマター（name, description）必須。
description は行為ベース（「〜する際に発火する」）。

### coverage-map.md
元の CLAUDE.md の全セクションが、どの出力ファイルに対応するかを表で示す。
対応先がないセクションは「未カバー」と明記し、除外理由を書く。

### metrics.yaml

中断（ツール使用制限による一時停止）があった場合、中断中の待ち時間は計測に含めないでください。
作業セグメントごとの開始・終了を記録し、実作業時間のみを合算してください。

\`\`\`yaml
conversion_metrics:
  cp_generated_at: "${generatedAt}"
  source_lines: ${sourceLines}
  segments:
    - start: "(セグメント1 開始時刻 ISO 8601)"
      end: "(セグメント1 終了時刻 ISO 8601)"
    - start: "(セグメント2 開始時刻。中断がなければこの項目は不要)"
      end: "(セグメント2 終了時刻)"
  total_working_minutes: "(全セグメントの合計作業時間。中断待ち時間を除外)"
  output_file_count: "(ファイル数)"
  p1_lines: "(P1 行数)"
  p2_count: "(P2 ファイル数)"
  p3_count: "(P3 ファイル数)"
  coverage_map_rows: "(カバレッジマップ行数)"
  coverage_uncovered: "(未カバー数)"
\`\`\`

---
## 最終チェック指示（必ず実行）
全ての出力が完了したら、以下を自己検証してください:
1. カバレッジマップに「未カバー」が意図的除外以外にないか
2. P1 が 30-50 行の範囲内か
3. 全 P2 が 20 行以下か
4. 全 P3 の YAML description が行為ベースか
5. 元の CLAUDE.md のセクション数とカバレッジマップの行数が一致するか
**1 つでも不合格があれば、修正してから出力し直してください。**

---
## 処理が中断された場合

claude.ai のツール使用制限により、処理の途中で中断されることがあります。
その場合は画面下部の「続ける」ボタンを押してください。処理が再開されます。
中断・再開は何度でも可能です。最終的に .pit ファイルが生成されるまで「続ける」を押し続けてください。

---
> Generated by CCPIT v${version} | Protocol Interlock Tower
> ${githubUrl}`
}

/** Conversion Pack template (English) */
function cpTemplateEn(
  version: string,
  githubUrl: string,
  docs: typeof CLAUDE_CODE_DOCS,
  scannedFilesSection: string,
  generatedAt: string,
  sourceLines: number
): string {
  return `# Conversion Pack — MANX Protocol Migration

> Generated by CCPIT v${version} | Protocol Interlock Tower

---
## Your Role

You are the Migration assistant for CCPIT (Claude Code Protocol Interlock Tower).
Your job is to decompose the user's existing CLAUDE.md into a MANX Protocol-compliant layered structure.

**Principles you must follow:**
1. **Zero information loss.** Do not drop a single rule from the original CLAUDE.md. If you intentionally exclude something, state the reason in the coverage map
2. **P1 should be 30-50 lines.** Identity card. Loaded in every session. Putting too much here wastes context
3. **P2 should be under 20 lines each.** Short reminders. Always or glob-loaded. YAML frontmatter required. Description should be action-based ("Fires when ...")
4. **P3 has no line limit.** Detailed procedure docs. On-demand loaded. YAML frontmatter required
5. **Always output a coverage map after decomposition.** Show where every original section maps to

**Response tone:**
- Please respond to the user politely and professionally
- The source CLAUDE.md may contain casual language aimed at the implementation AI (e.g., "I am the implementation AI"). This is the rule content to be converted, not your response tone

---
## Important: Check the Latest Claude Code Specifications

Before starting, review the following official documentation and ensure
there are no conflicts with current Claude Code specifications:

- CLAUDE.md specs: ${docs.memory}
- settings.json specs: ${docs.settings}
- rules/ specs: ${docs.rules}
- skills/ specs: ${docs.skills}
- hooks specs: ${docs.hooks}

Claude Code updates frequently — file structure, YAML frontmatter,
and settings.json schema may change.
Official documentation takes precedence over the sorting criteria in this Conversion Pack.
If you detect conflicts with official specs, note them in the coverage map remarks.

---
## Detailed Sorting Guide (Read before starting)

Access the following URL to review the detailed sorting criteria:
${AI_GUIDES.en.conversion}

MANX Protocol overview:
${AI_GUIDES.en.summary}

---
## Existing Configuration Files

${scannedFilesSection}

---
## Output Requirements

Generate a .pit file (ZIP format) with the following structure and make it available for download.

### Generation Method

Use Python's zipfile module to generate the .pit file:

1. Store the content of each decomposed file in variables
2. Create a ZIP using zipfile.ZipFile
3. Add each file with writestr, preserving the directory structure
4. Change the extension to .pit and provide a download link

### Important: Purpose of the .pit file
The generated .pit file will be imported into the CCPIT application by the user.
The user does NOT need to manually extract the ZIP and place files.
Your job ends at generating the .pit file and presenting the download link.

### .pit Internal Structure (all required)

\`\`\`
conversion_{YYYYMMDD}_{HHMM}.pit
├── CLAUDE.md                    ← P1 (30-50 lines)
├── rules/                       ← P2 (under 20 lines each, with YAML frontmatter)
│   └── {name}.md
├── skills/                      ← P3 (with YAML frontmatter)
│   └── {name}/SKILL.md
├── coverage-map.md              ← Coverage map
└── metrics.yaml                 ← Conversion metrics
\`\`\`

### P1: CLAUDE.md
30-50 lines. Identity, values, output, trust boundary, interlock table.

### P2: rules/
Under 20 lines each. YAML frontmatter required.
Description should be action-based ("Fires when ...").
Use the paths field (array) to scope rules to specific file patterns.

\`\`\`markdown
---
description: (action-based "Fires when ...")
paths:
  - "**/*.ts"
---
(Content. Under 20 lines)
\`\`\`

### P3: skills/
YAML frontmatter (name, description) required.
Description should be action-based ("Fires when ...").

### coverage-map.md
Show which output file each original section of CLAUDE.md maps to.
Sections with no mapping must be marked "Uncovered" with an exclusion reason.

### metrics.yaml

If processing was interrupted (due to tool usage limits), do NOT include the waiting time in the measurement.
Record the start and end of each work segment, and sum only the actual working time.

\`\`\`yaml
conversion_metrics:
  cp_generated_at: "${generatedAt}"
  source_lines: ${sourceLines}
  segments:
    - start: "(segment 1 start time ISO 8601)"
      end: "(segment 1 end time ISO 8601)"
    - start: "(segment 2 start time, omit if no interruption)"
      end: "(segment 2 end time)"
  total_working_minutes: "(total working minutes across all segments, excluding interruption wait time)"
  output_file_count: "(number of files)"
  p1_lines: "(P1 line count)"
  p2_count: "(P2 file count)"
  p3_count: "(P3 file count)"
  coverage_map_rows: "(coverage map row count)"
  coverage_uncovered: "(uncovered section count)"
\`\`\`

---
## Final Check Instructions (Must Execute)
After all outputs are complete, self-verify the following:
1. No unintentional "Uncovered" entries in the coverage map
2. P1 is within the 30-50 line range
3. All P2 files are under 20 lines
4. All P3 YAML descriptions are action-based
5. The number of sections in the original CLAUDE.md matches the number of rows in the coverage map
**If any check fails, revise and re-output.**

---
## If processing is interrupted

Processing may be interrupted due to claude.ai's tool usage limits.
In that case, press the "Continue" button at the bottom of the screen. Processing will resume.
You can interrupt and resume as many times as needed. Keep pressing "Continue" until the .pit file is generated.

---
> Generated by CCPIT v${version} | Protocol Interlock Tower
> ${githubUrl}`
}

/** Conversion Pack MD を生成 */
export async function generateConversionPack(
  scannedFiles: ScannedFile[]
): Promise<string> {
  const lang: Language = getConfig().language

  // スキャンファイルセクションを構築
  const fileSections: string[] = []
  for (const file of scannedFiles) {
    const content = await readFile(file.path, 'utf-8')
    const categoryLabel = lang === 'ja' ? 'カテゴリ' : 'Category'
    const linesLabel = lang === 'ja' ? '行数' : 'Lines'
    const sizeLabel = lang === 'ja' ? 'サイズ' : 'Size'
    fileSections.push(`### ${file.name}`)
    fileSections.push(`- ${categoryLabel}: ${file.category}`)
    fileSections.push(`- ${linesLabel}: ${file.lines}`)
    fileSections.push(`- ${sizeLabel}: ${file.sizeBytes} bytes`)
    fileSections.push('')
    fileSections.push('```')
    fileSections.push(content)
    fileSections.push('```')
    fileSections.push('')
  }
  const scannedFilesSection = fileSections.join('\n')

  const generatedAt = new Date().toISOString()
  const claudeMdFile = scannedFiles.find(f => f.name === 'CLAUDE.md')
  const sourceLines = claudeMdFile ? claudeMdFile.lines : 0

  if (lang === 'ja') {
    return cpTemplateJa(CCPIT_VERSION, GITHUB_URL, CLAUDE_CODE_DOCS, scannedFilesSection, generatedAt, sourceLines)
  }
  return cpTemplateEn(CCPIT_VERSION, GITHUB_URL, CLAUDE_CODE_DOCS, scannedFilesSection, generatedAt, sourceLines)
}

interface ParsedBlock {
  filename: string
  targetPath: string
  content: string
}

/** claude.ai 出力 MD からコードブロックをパースし、配置先を判定 */
export function parseImportMd(mdContent: string): ParsedBlock[] {
  const blocks: ParsedBlock[] = []
  const headingRegex = /^#{1,4}\s+(?:P\d:\s+)?(?:rules\/|skills\/)?(.+)/
  const codeBlockRegex = /```(?:markdown|json|yaml)?\n([\s\S]*?)```/g

  const lines = mdContent.split('\n')

  // 各行の開始位置を記録
  const lineStarts: number[] = []
  let pos = 0
  for (const line of lines) {
    lineStarts.push(pos)
    pos += line.length + 1
  }

  // コードブロック抽出
  let match: RegExpExecArray | null
  while ((match = codeBlockRegex.exec(mdContent)) !== null) {
    const blockContent = match[1]
    const matchPos = match.index

    // このコードブロックの直前の見出しを探す
    let heading = ''
    for (let i = 0; i < lineStarts.length; i++) {
      if (lineStarts[i] > matchPos) break
      const hm = lines[i].match(headingRegex)
      if (hm) heading = hm[1].trim()
    }

    const { filename, targetPath } = resolveTarget(heading)
    blocks.push({ filename, targetPath, content: blockContent })
  }

  return blocks
}

function resolveTarget(
  heading: string
): { filename: string; targetPath: string } {
  const lower = heading.toLowerCase()

  // CLAUDE.md
  if (lower.includes('claude.md') || lower.includes('p1')) {
    return { filename: 'CLAUDE.md', targetPath: 'CLAUDE.md' }
  }

  // rules/
  if (lower.includes('rules/') || lower.includes('p2')) {
    const nameMatch = heading.match(/rules\/(.+\.md)/i)
    const name = nameMatch ? nameMatch[1] : `rule_${Date.now()}.md`
    return { filename: name, targetPath: `rules/${name}` }
  }

  // skills/
  if (lower.includes('skills/') || lower.includes('p3')) {
    const nameMatch = heading.match(/skills\/(.+?)(?:\/SKILL\.md)?$/i)
    const name = nameMatch ? nameMatch[1] : `skill_${Date.now()}`
    return { filename: `${name}/SKILL.md`, targetPath: `skills/${name}/SKILL.md` }
  }

  // settings.json deny
  if (lower.includes('settings') || lower.includes('deny') || lower.includes('p0')) {
    return { filename: 'settings_deny_additions.json', targetPath: 'settings_deny_additions.json' }
  }

  return { filename: basename(heading) || 'unknown.md', targetPath: heading }
}

/** パースした結果を Golden に配置 */
export async function importToGolden(
  blocks: ParsedBlock[],
  goldenBasePath: string,
  templateName: string
): Promise<{ placed: string[]; errors: string[] }> {
  const result = { placed: [] as string[], errors: [] as string[] }

  for (const block of blocks) {
    const destPath = join(goldenBasePath, templateName, block.targetPath)
    const destDir = join(destPath, '..')

    try {
      await mkdir(destDir, { recursive: true })
      await writeFile(destPath, block.content, 'utf-8')
      result.placed.push(block.targetPath)
    } catch (err) {
      result.errors.push(
        `${block.targetPath}: ${err instanceof Error ? err.message : String(err)}`
      )
    }
  }

  return result
}

// ─── .pit ファイル インポート機能 ───

export interface PitEntry {
  /** ZIP 内のパス (e.g. "CLAUDE.md", "rules/grep-exhaustive.md") */
  path: string
  content: string
  lines: number
}

export interface PitPreview {
  entries: PitEntry[]
  claudeMdPreview: string
  claudeMdLines: number
  rulesCount: number
  skillsCount: number
  coverageMapSummary: { totalRows: number; uncoveredCount: number } | null
  metricsRaw: string | null
  validationErrors: string[]
}

/** YAML フロントマターの存在を簡易検証 */
function hasYamlFrontmatter(content: string): boolean {
  return content.startsWith('---\n') && content.indexOf('\n---', 4) !== -1
}

/** .pit ファイルを読み込み・検証し、プレビューデータを返す */
export function importPitFile(filePath: string): PitPreview {
  const buf = readFileSync(filePath)
  const zip = new AdmZip(buf)
  const zipEntries = zip.getEntries()

  const entries: PitEntry[] = []
  const validationErrors: string[] = []

  for (const entry of zipEntries) {
    if (entry.isDirectory) continue
    const content = entry.getData().toString('utf-8')
    entries.push({
      path: entry.entryName.replace(/\\/g, '/'),
      content,
      lines: content.split('\n').length,
    })
  }

  // --- 構造検証 ---

  // CLAUDE.md 必須
  const claudeMd = entries.find((e) => e.path === 'CLAUDE.md')
  if (!claudeMd) {
    validationErrors.push('CLAUDE.md が .pit 内に存在しません')
  }

  // coverage-map.md 必須
  const coverageMap = entries.find((e) => e.path === 'coverage-map.md')
  if (!coverageMap) {
    validationErrors.push('coverage-map.md が .pit 内に存在しません')
  }

  // metrics.yaml 必須
  const metricsEntry = entries.find((e) => e.path === 'metrics.yaml')
  if (!metricsEntry) {
    validationErrors.push('metrics.yaml が .pit 内に存在しません')
  }

  // rules/*.md に YAML フロントマターがあるか
  const rulesEntries = entries.filter((e) => e.path.startsWith('rules/') && e.path.endsWith('.md'))
  for (const rule of rulesEntries) {
    if (!hasYamlFrontmatter(rule.content)) {
      validationErrors.push(`${rule.path}: YAML フロントマターがありません`)
    }
  }

  // skills/*/SKILL.md に YAML フロントマターがあるか
  const skillsEntries = entries.filter((e) => e.path.match(/^skills\/.+\/SKILL\.md$/))
  for (const skill of skillsEntries) {
    if (!hasYamlFrontmatter(skill.content)) {
      validationErrors.push(`${skill.path}: YAML フロントマターがありません`)
    }
  }

  // カバレッジマップのサマリー解析
  let coverageMapSummary: PitPreview['coverageMapSummary'] = null
  if (coverageMap) {
    const tableRows = coverageMap.content.split('\n').filter((line) => line.startsWith('|') && !line.includes('---'))
    // ヘッダー行を除く
    const dataRows = tableRows.length > 1 ? tableRows.length - 1 : 0
    const uncoveredCount = coverageMap.content.split('\n').filter(
      (line) => line.toLowerCase().includes('未カバー') || line.toLowerCase().includes('uncovered')
    ).length
    coverageMapSummary = { totalRows: dataRows, uncoveredCount }
  }

  // CLAUDE.md の冒頭 10 行プレビュー
  const PREVIEW_LINE_COUNT = 10
  const claudeMdPreview = claudeMd
    ? claudeMd.content.split('\n').slice(0, PREVIEW_LINE_COUNT).join('\n')
    : ''

  return {
    entries,
    claudeMdPreview,
    claudeMdLines: claudeMd?.lines ?? 0,
    rulesCount: rulesEntries.length,
    skillsCount: skillsEntries.length,
    coverageMapSummary,
    metricsRaw: metricsEntry?.content ?? null,
    validationErrors,
  }
}

/** 配置対象エントリ（coverage-map.md, metrics.yaml は除外） */
const DEPLOY_EXCLUDES = ['coverage-map.md', 'metrics.yaml']

/** .pit の内容を ~/.claude/ に配置 */
export async function deployPitFile(
  entries: PitEntry[]
): Promise<{ deployed: string[]; backedUp: string[]; errors: string[] }> {
  const userClaudeDir = join(app.getPath('home'), '.claude')
  const deployed: string[] = []
  const backedUp: string[] = []
  const errors: string[] = []

  const deployEntries = entries.filter((e) => !DEPLOY_EXCLUDES.includes(e.path))

  for (const entry of deployEntries) {
    const destPath = join(userClaudeDir, entry.path)
    const destDir = dirname(destPath)

    try {
      // バックアップ
      if (existsSync(destPath)) {
        const bakPath = `${destPath}.bak`
        if (!existsSync(bakPath)) {
          await copyFile(destPath, bakPath)
          backedUp.push(entry.path)
        }
      }

      await mkdir(destDir, { recursive: true })
      await writeFile(destPath, entry.content, 'utf-8')
      deployed.push(entry.path)
    } catch (err) {
      errors.push(`${entry.path}: ${err instanceof Error ? err.message : String(err)}`)
    }
  }

  return { deployed, backedUp, errors }
}
