import { readdir, readFile, stat, mkdir, writeFile } from 'fs/promises'
import { join, basename } from 'path'
import { existsSync } from 'fs'
import { app } from 'electron'
import { getConfig, type Language } from './appConfig'
import { CCPIT_VERSION, GITHUB_URL, CLAUDE_CODE_DOCS, AI_GUIDES } from './constants'

interface ScannedFile {
  path: string
  name: string
  lines: number
  sizeBytes: number
  category: 'claude-md' | 'rules' | 'skills' | 'settings' | 'other'
}

/** CC 構成ファイルの検出対象パターン */
const SCAN_TARGETS = [
  { glob: 'CLAUDE.md', category: 'claude-md' as const },
  { glob: '.claude/settings.json', category: 'settings' as const },
  { glob: '.claude/settings.local.json', category: 'settings' as const },
]

const SCAN_DIRS = [
  { dir: '.claude/rules', category: 'rules' as const },
  { dir: '.claude/skills', category: 'skills' as const },
]

/** 指定パスの CC 構成ファイルをスキャン */
export async function scanProject(projectPath: string): Promise<ScannedFile[]> {
  const results: ScannedFile[] = []

  // 単体ファイルチェック
  for (const target of SCAN_TARGETS) {
    const fullPath = join(projectPath, target.glob)
    if (existsSync(fullPath)) {
      const content = await readFile(fullPath, 'utf-8')
      const info = await stat(fullPath)
      results.push({
        path: fullPath,
        name: target.glob,
        lines: content.split('\n').length,
        sizeBytes: info.size,
        category: target.category,
      })
    }
  }

  // ディレクトリスキャン
  for (const { dir, category } of SCAN_DIRS) {
    const dirPath = join(projectPath, dir)
    if (!existsSync(dirPath)) continue
    try {
      const entries = await readdir(dirPath, { withFileTypes: true })
      for (const entry of entries) {
        if (!entry.isFile()) continue
        const fullPath = join(dirPath, entry.name)
        const content = await readFile(fullPath, 'utf-8')
        const info = await stat(fullPath)
        results.push({
          path: fullPath,
          name: `${dir}/${entry.name}`,
          lines: content.split('\n').length,
          sizeBytes: info.size,
          category,
        })
      }
    } catch {
      // ディレクトリ読み取り失敗は無視
    }
  }

  // ~/.claude/ もスキャン
  const userClaudeDir = join(app.getPath('home'), '.claude')
  if (existsSync(userClaudeDir) && !projectPath.includes('.claude')) {
    for (const target of SCAN_TARGETS) {
      const name = basename(target.glob)
      const fullPath = join(userClaudeDir, name)
      if (existsSync(fullPath) && !results.some((r) => r.path === fullPath)) {
        const content = await readFile(fullPath, 'utf-8')
        const info = await stat(fullPath)
        results.push({
          path: fullPath,
          name: `~/.claude/${name}`,
          lines: content.split('\n').length,
          sizeBytes: info.size,
          category: target.category,
        })
      }
    }

    for (const { dir, category } of SCAN_DIRS) {
      const dirName = dir.replace('.claude/', '')
      const dirPath = join(userClaudeDir, dirName)
      if (!existsSync(dirPath)) continue
      try {
        const entries = await readdir(dirPath, { withFileTypes: true })
        for (const entry of entries) {
          if (!entry.isFile()) continue
          const fullPath = join(dirPath, entry.name)
          if (results.some((r) => r.path === fullPath)) continue
          const content = await readFile(fullPath, 'utf-8')
          const info = await stat(fullPath)
          results.push({
            path: fullPath,
            name: `~/.claude/${dirName}/${entry.name}`,
            lines: content.split('\n').length,
            sizeBytes: info.size,
            category,
          })
        }
      } catch {
        // skip
      }
    }
  }

  return results
}

/** Conversion Pack テンプレート（日本語） */
function cpTemplateJa(
  version: string,
  githubUrl: string,
  docs: typeof CLAUDE_CODE_DOCS,
  scannedFilesSection: string
): string {
  return `# Conversion Pack — MANX Protocol Migration

> Generated by CCPIT v${version} | Protocol Interlock Tower

---
## あなたの役割

あなたは CCPIT（Claude Code Protocol Interlock Tower）の Migration アシスタントです。
ユーザーの既存 CLAUDE.md を MANX Protocol に準拠した階層構造に分解します。

**あなたが守るべき原則:**
1. **情報欠落ゼロ。** 元の CLAUDE.md に書かれたルールは 1 行も落とさない。意図的に除外する場合のみ、カバレッジマップに理由を明記する
2. **P1 は 30〜50 行。** 身分証明書。全セッションで常時ロードされる。ここに入れすぎるとコンテキストを浪費する
3. **P2 は各 20 行以下。** 短いリマインダー。常時 or glob でロード。YAML フロントマター付き。description は行為ベース（「〜する際に発火する」）
4. **P3 は行数制限なし。** 詳細手順書。オンデマンドロード。YAML フロントマター付き
5. **分解後に必ずカバレッジマップを出力。** 元の全セクションの対応先を漏れなく示す

---
## 重要: 最新の Claude Code 仕様を確認してください

作業を開始する前に、以下の公式ドキュメントを必ず参照し、
現在の Claude Code の仕様と矛盾がないことを確認してください:

- CLAUDE.md の仕様: ${docs.memory}
- settings.json の仕様: ${docs.settings}
- rules/ の仕様: ${docs.rules}
- skills/ の仕様: ${docs.skills}
- hooks の仕様: ${docs.hooks}

Claude Code は更新が早く、ファイル構造・YAML フロントマター・
settings.json のスキーマが変わる可能性があります。
本 Conversion Pack の振り分け基準より公式ドキュメントが優先します。
公式仕様と矛盾を検出した場合は、カバレッジマップの備考欄に記載してください。

---
## 詳細な振り分けガイド（必ず読んでから作業を開始してください）

以下の URL にアクセスし、振り分け基準の詳細を確認してください:
${AI_GUIDES.ja.conversion}

MANX Protocol の全体像:
${AI_GUIDES.ja.summary}

---
## 既存構成ファイル

${scannedFilesSection}

---
## 出力要求

以下の 4 つを **必ず全て** 出力してください:

### 出力 1: P1 CLAUDE.md（30〜50 行）
\`\`\`markdown
（コンバート後の CLAUDE.md）
\`\`\`

### 出力 2: P2 rules/ ファイル群
各ファイルを個別のコードブロックで出力。YAML フロントマター必須。

#### rules/{name}.md
\`\`\`markdown
---
description: （行為ベース「〜する際に発火する」）
globs: （該当ファイルパターン。なければ空）
---
（内容。20 行以下）
\`\`\`

### 出力 3: P3 skills/ ファイル群
各ファイルを個別のコードブロックで出力。YAML フロントマター必須。

#### skills/{name}/SKILL.md
\`\`\`markdown
---
name: {name}
description: （行為ベース「〜する際に発火する」）
---
（内容）
\`\`\`

### 出力 4: カバレッジマップ（最重要）
元の CLAUDE.md の **全セクション** が、どの出力ファイルに対応するかを表で示してください。
**対応先がないセクションは「未カバー」と明記し、除外理由を書いてください。**

| 元のセクション | 行範囲（目安） | 出力先 | 備考 |
|--------------|-------------|--------|------|
| （例）ヘッダー | L1-7 | P1 CLAUDE.md | 圧縮 |
| ... | ... | ... | ... |
| （例）該当なし | L620-632 | 未カバー | 理由: 廃止された運用ルール |

---
## 最終チェック指示（必ず実行）
全ての出力が完了したら、以下を自己検証してください:
1. カバレッジマップに「未カバー」が意図的除外以外にないか
2. P1 が 30-50 行の範囲内か
3. 全 P2 が 20 行以下か
4. 全 P3 の YAML description が行為ベースか
5. 元の CLAUDE.md のセクション数とカバレッジマップの行数が一致するか
**1 つでも不合格があれば、修正してから出力し直してください。**

---
> Generated by CCPIT v${version} | Protocol Interlock Tower
> ${githubUrl}`
}

/** Conversion Pack template (English) */
function cpTemplateEn(
  version: string,
  githubUrl: string,
  docs: typeof CLAUDE_CODE_DOCS,
  scannedFilesSection: string
): string {
  return `# Conversion Pack — MANX Protocol Migration

> Generated by CCPIT v${version} | Protocol Interlock Tower

---
## Your Role

You are the Migration assistant for CCPIT (Claude Code Protocol Interlock Tower).
Your job is to decompose the user's existing CLAUDE.md into a MANX Protocol-compliant layered structure.

**Principles you must follow:**
1. **Zero information loss.** Do not drop a single rule from the original CLAUDE.md. If you intentionally exclude something, state the reason in the coverage map
2. **P1 should be 30-50 lines.** Identity card. Loaded in every session. Putting too much here wastes context
3. **P2 should be under 20 lines each.** Short reminders. Always or glob-loaded. YAML frontmatter required. Description should be action-based ("Fires when ...")
4. **P3 has no line limit.** Detailed procedure docs. On-demand loaded. YAML frontmatter required
5. **Always output a coverage map after decomposition.** Show where every original section maps to

---
## Important: Check the Latest Claude Code Specifications

Before starting, review the following official documentation and ensure
there are no conflicts with current Claude Code specifications:

- CLAUDE.md specs: ${docs.memory}
- settings.json specs: ${docs.settings}
- rules/ specs: ${docs.rules}
- skills/ specs: ${docs.skills}
- hooks specs: ${docs.hooks}

Claude Code updates frequently — file structure, YAML frontmatter,
and settings.json schema may change.
Official documentation takes precedence over the sorting criteria in this Conversion Pack.
If you detect conflicts with official specs, note them in the coverage map remarks.

---
## Detailed Sorting Guide (Read before starting)

Access the following URL to review the detailed sorting criteria:
${AI_GUIDES.en.conversion}

MANX Protocol overview:
${AI_GUIDES.en.summary}

---
## Existing Configuration Files

${scannedFilesSection}

---
## Output Requirements

You **must** output all 4 of the following:

### Output 1: P1 CLAUDE.md (30-50 lines)
\`\`\`markdown
(Converted CLAUDE.md)
\`\`\`

### Output 2: P2 rules/ files
Output each file in a separate code block. YAML frontmatter required.

#### rules/{name}.md
\`\`\`markdown
---
description: (action-based "Fires when ...")
globs: (matching file patterns, or empty)
---
(Content. Under 20 lines)
\`\`\`

### Output 3: P3 skills/ files
Output each file in a separate code block. YAML frontmatter required.

#### skills/{name}/SKILL.md
\`\`\`markdown
---
name: {name}
description: (action-based "Fires when ...")
---
(Content)
\`\`\`

### Output 4: Coverage Map (Most Important)
Show which output file each **original section** of CLAUDE.md maps to.
**Sections with no mapping must be marked "Uncovered" with an exclusion reason.**

| Original Section | Line Range (approx) | Output | Remarks |
|-----------------|---------------------|--------|---------|
| (e.g.) Header | L1-7 | P1 CLAUDE.md | Compressed |
| ... | ... | ... | ... |
| (e.g.) N/A | L620-632 | Uncovered | Reason: deprecated rule |

---
## Final Check Instructions (Must Execute)
After all outputs are complete, self-verify the following:
1. No unintentional "Uncovered" entries in the coverage map
2. P1 is within the 30-50 line range
3. All P2 files are under 20 lines
4. All P3 YAML descriptions are action-based
5. The number of sections in the original CLAUDE.md matches the number of rows in the coverage map
**If any check fails, revise and re-output.**

---
> Generated by CCPIT v${version} | Protocol Interlock Tower
> ${githubUrl}`
}

/** Conversion Pack MD を生成 */
export async function generateConversionPack(
  scannedFiles: ScannedFile[]
): Promise<string> {
  const lang: Language = getConfig().language

  // スキャンファイルセクションを構築
  const fileSections: string[] = []
  for (const file of scannedFiles) {
    const content = await readFile(file.path, 'utf-8')
    const categoryLabel = lang === 'ja' ? 'カテゴリ' : 'Category'
    const linesLabel = lang === 'ja' ? '行数' : 'Lines'
    const sizeLabel = lang === 'ja' ? 'サイズ' : 'Size'
    fileSections.push(`### ${file.name}`)
    fileSections.push(`- ${categoryLabel}: ${file.category}`)
    fileSections.push(`- ${linesLabel}: ${file.lines}`)
    fileSections.push(`- ${sizeLabel}: ${file.sizeBytes} bytes`)
    fileSections.push('')
    fileSections.push('```')
    fileSections.push(content)
    fileSections.push('```')
    fileSections.push('')
  }
  const scannedFilesSection = fileSections.join('\n')

  if (lang === 'ja') {
    return cpTemplateJa(CCPIT_VERSION, GITHUB_URL, CLAUDE_CODE_DOCS, scannedFilesSection)
  }
  return cpTemplateEn(CCPIT_VERSION, GITHUB_URL, CLAUDE_CODE_DOCS, scannedFilesSection)
}

interface ParsedBlock {
  filename: string
  targetPath: string
  content: string
}

/** claude.ai 出力 MD からコードブロックをパースし、配置先を判定 */
export function parseImportMd(mdContent: string): ParsedBlock[] {
  const blocks: ParsedBlock[] = []
  const headingRegex = /^#{1,4}\s+(?:P\d:\s+)?(?:rules\/|skills\/)?(.+)/
  const codeBlockRegex = /```(?:markdown|json|yaml)?\n([\s\S]*?)```/g

  const lines = mdContent.split('\n')

  // 各行の開始位置を記録
  const lineStarts: number[] = []
  let pos = 0
  for (const line of lines) {
    lineStarts.push(pos)
    pos += line.length + 1
  }

  // コードブロック抽出
  let match: RegExpExecArray | null
  while ((match = codeBlockRegex.exec(mdContent)) !== null) {
    const blockContent = match[1]
    const matchPos = match.index

    // このコードブロックの直前の見出しを探す
    let heading = ''
    for (let i = 0; i < lineStarts.length; i++) {
      if (lineStarts[i] > matchPos) break
      const hm = lines[i].match(headingRegex)
      if (hm) heading = hm[1].trim()
    }

    const { filename, targetPath } = resolveTarget(heading)
    blocks.push({ filename, targetPath, content: blockContent })
  }

  return blocks
}

function resolveTarget(
  heading: string
): { filename: string; targetPath: string } {
  const lower = heading.toLowerCase()

  // CLAUDE.md
  if (lower.includes('claude.md') || lower.includes('p1')) {
    return { filename: 'CLAUDE.md', targetPath: 'CLAUDE.md' }
  }

  // rules/
  if (lower.includes('rules/') || lower.includes('p2')) {
    const nameMatch = heading.match(/rules\/(.+\.md)/i)
    const name = nameMatch ? nameMatch[1] : `rule_${Date.now()}.md`
    return { filename: name, targetPath: `rules/${name}` }
  }

  // skills/
  if (lower.includes('skills/') || lower.includes('p3')) {
    const nameMatch = heading.match(/skills\/(.+?)(?:\/SKILL\.md)?$/i)
    const name = nameMatch ? nameMatch[1] : `skill_${Date.now()}`
    return { filename: `${name}/SKILL.md`, targetPath: `skills/${name}/SKILL.md` }
  }

  // settings.json deny
  if (lower.includes('settings') || lower.includes('deny') || lower.includes('p0')) {
    return { filename: 'settings_deny_additions.json', targetPath: 'settings_deny_additions.json' }
  }

  return { filename: basename(heading) || 'unknown.md', targetPath: heading }
}

/** パースした結果を Golden に配置 */
export async function importToGolden(
  blocks: ParsedBlock[],
  goldenBasePath: string,
  templateName: string
): Promise<{ placed: string[]; errors: string[] }> {
  const result = { placed: [] as string[], errors: [] as string[] }

  for (const block of blocks) {
    const destPath = join(goldenBasePath, templateName, block.targetPath)
    const destDir = join(destPath, '..')

    try {
      await mkdir(destDir, { recursive: true })
      await writeFile(destPath, block.content, 'utf-8')
      result.placed.push(block.targetPath)
    } catch (err) {
      result.errors.push(
        `${block.targetPath}: ${err instanceof Error ? err.message : String(err)}`
      )
    }
  }

  return result
}
